const char *fallbackShader_pshadow_vp =
"attribute vec3 attr_Position;\n"
"attribute vec3 attr_Normal;\n"
"\n"
"uniform mat4 u_ModelMatrix;\n"
"\n"
"layout(shared) uniform ViewMatrices\n"
"{\n"
"    uniform mat4 u_ViewMatrices[NUM_VIEWS];\n"
"};\n"
"layout(shared) uniform ProjectionMatrix\n"
"{\n"
"    uniform mat4 u_ProjectionMatrix[NUM_VIEWS];\n"
"};\n"
"\n"
"varying vec3   var_Position;\n"
"varying vec3   var_Normal;\n"
"\n"
"\n"
"void main()\n"
"{\n"
"	gl_Position = u_ProjectionMatrix[gl_ViewID_OVR] * (u_ViewMatrices[gl_ViewID_OVR] * (u_ModelMatrix * vec4(attr_Position, 1.0)));\n"
"\n"
"	var_Position  = attr_Position;\n"
"	var_Normal    = attr_Normal;\n"
"}\n"
;
