const char *fallbackShader_texturecolor_vp =
"attribute vec3 attr_Position;\n"
"attribute vec4 attr_TexCoord0;\n"
"\n"
"uniform mat4 u_ModelMatrix;\n"
"\n"
"layout(shared) uniform ViewMatrices\n"
"{\n"
"    uniform mat4 u_ViewMatrices[NUM_VIEWS];\n"
"};\n"
"layout(shared) uniform ProjectionMatrix\n"
"{\n"
"    uniform mat4 u_ProjectionMatrix[NUM_VIEWS];\n"
"};\n"
"\n"
"varying vec2   var_Tex1;\n"
"\n"
"\n"
"void main()\n"
"{\n"
"	gl_Position = u_ProjectionMatrix[gl_ViewID_OVR] * (u_ViewMatrices[gl_ViewID_OVR] * (u_ModelMatrix * vec4(attr_Position, 1.0)));\n"
"	var_Tex1 = attr_TexCoord0.st;\n"
"}\n"
;
